### ISSUE TITLE
Clarification of forked status

### ISSUE THREAD

**Issue by indolering** [dionjwa/nodejs-std#25]
The readme states,

>Alternative to the [nodejs haxelib](http://lib.haxe.org/p/nodejs) library, forked due to a lack of maintenance form the other library.

However, the Haxe lib entry the link sends us to simply links back to this project:

> Website    https://github.com/dionjwa/nodejs-std/ 

... huh?

**Comment by dionjwa** [comment]
When the haxelib site upgraded to serve haxev3 compatible libraries only, I took the nodejs haxelib name, whereas previously, it was using a different repository: http://lib.haxe.org/legacy/p/nodejs. I'll upgrade the README to reflect this.

**Comment by dionjwa** [comment]
Fixed https://github.com/dionjwa/nodejs-std/commit/ea2662a80b7f335703b9c58d37268fafd74cf259
