### ISSUE TITLE
Haxe 3.2

### ISSUE THREAD

**Issue by NicoM1** [dionjwa/nodejs-std#42]
Is this working on 3.2? I'm getting:

`C:\HaxeToolkit\haxe\lib\nodejs/2,2,7/js/node/MongoDb.hx:161: characters 9-69 : Type not found : NodeListener`

**Comment by dionjwa** [comment]
Yeah, there's been some API changes. I'm going to deprecate this library, see:
https://groups.google.com/forum/#!topic/haxelang/UTYawE745yM

**Comment by dionjwa** [comment]
Hi. I'm not longer maintaining this library, I'm moving my efforts over to https://github.com/HaxeFoundation/hxnodejs
